# Generated by Django 3.1.3 on 2021-01-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_server', '0002_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.TextField(max_length=5, verbose_name='类别 零食等4个'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='intro',
            field=models.TextField(max_length=100, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.TextField(max_length=30, verbose_name='商品名称'),
        ),
    ]
