# Generated by Django 3.1.3 on 2021-01-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_server', '0003_auto_20210103_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='begofftime',
            field=models.CharField(default='', max_length=5000, verbose_name='请假的时间'),
        ),
    ]
