# Generated by Django 3.1.3 on 2021-01-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_server', '0004_worker_begofftime'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskItem',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.TextField(max_length=30, verbose_name='工作人员id')),
                ('category', models.TextField(max_length=10, verbose_name='类别 上货等几个')),
                ('time', models.TextField(max_length=50, verbose_name='时间')),
                ('detail', models.TextField(max_length=400, verbose_name='简介')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='tasknum',
            field=models.CharField(default=0, max_length=15, verbose_name='任务数目'),
            preserve_default=False,
        ),
    ]
