# Generated by Django 3.1.3 on 2021-01-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_server', '0005_auto_20210104_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='tasknum',
            field=models.CharField(default='0', max_length=15, verbose_name='任务数目'),
        ),
    ]
