# Generated by Django 3.1.3 on 2021-01-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_server', '0006_auto_20210104_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.TextField(max_length=30, verbose_name='任务id')),
                ('details', models.TextField(default='', max_length=1000, verbose_name='细节')),
            ],
        ),
    ]
