# Generated by Django 3.1.3 on 2021-01-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_server', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='customid',
            field=models.TextField(default='', max_length=20, verbose_name='客户id，系统任务为全0'),
        ),
    ]
