# Generated by Django 3.1.3 on 2021-01-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_server', '0008_taskitem_customid'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=15, verbose_name='用户手机号或账号')),
                ('nickname', models.CharField(max_length=5, verbose_name='用户姓名')),
                ('cart', models.CharField(max_length=5000, verbose_name='购物车')),
                ('record', models.CharField(max_length=5, verbose_name='购物记录')),
            ],
        ),
    ]
