# Generated by Django 3.1.3 on 2021-01-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_server', '0009_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cart',
            field=models.TextField(max_length=5000, verbose_name='购物车'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='用户姓名'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='record',
            field=models.TextField(max_length=5000, verbose_name='购物记录'),
        ),
    ]
